<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Create default admin user
        User::create([
            'name' => 'Admin User',
            'email' => 'admin@clocation.com',
            'password' => Hash::make('admin123'),
            'firstName' => 'Admin',
            'lastName' => 'User',
            'role' => 'admin',
            'status' => 'active',
            'department' => 'IT',
            'position' => 'System Administrator',
            'phone' => '+1234567890',
            'address' => '123 Admin Street',
            'hireDate' => now(),
            'salary' => 75000.00,
            'contractStart' => now(),
            'contractEnd' => now()->addYears(2),
            'medicalVisitStart' => now(),
            'medicalVisitEnd' => now()->addYear(),
            'derogationStart' => null,
            'derogationEnd' => null,
            'inductionStart' => now(),
            'inductionEnd' => now()->addDays(30),
            'cnssNumber' => 'CNSS001',
            'payrollNumber' => 'PAY001',
        ]);

        // Create sample manager user
        User::create([
            'name' => 'John Manager',
            'email' => 'manager@clocation.com',
            'password' => Hash::make('manager123'),
            'firstName' => 'John',
            'lastName' => 'Manager',
            'role' => 'manager',
            'status' => 'active',
            'department' => 'Operations',
            'position' => 'Fleet Manager',
            'phone' => '+1234567891',
            'address' => '456 Manager Avenue',
            'hireDate' => now(),
            'salary' => 65000.00,
            'contractStart' => now(),
            'contractEnd' => now()->addYears(3),
            'medicalVisitStart' => now(),
            'medicalVisitEnd' => now()->addYear(),
            'derogationStart' => null,
            'derogationEnd' => null,
            'inductionStart' => now(),
            'inductionEnd' => now()->addDays(15),
            'cnssNumber' => 'CNSS002',
            'payrollNumber' => 'PAY002',
        ]);

        // Create sample employee user
        User::create([
            'name' => 'Jane Employee',
            'email' => 'employee@clocation.com',
            'password' => Hash::make('employee123'),
            'firstName' => 'Jane',
            'lastName' => 'Employee',
            'role' => 'employee',
            'status' => 'active',
            'department' => 'Sales',
            'position' => 'Sales Representative',
            'phone' => '+1234567892',
            'address' => '789 Employee Road',
            'hireDate' => now(),
            'salary' => 45000.00,
            'contractStart' => now(),
            'contractEnd' => now()->addYear(),
            'medicalVisitStart' => now(),
            'medicalVisitEnd' => now()->addYear(),
            'derogationStart' => now(),
            'derogationEnd' => now()->addMonths(6),
            'inductionStart' => now(),
            'inductionEnd' => now()->addDays(7),
            'cnssNumber' => 'CNSS003',
            'payrollNumber' => 'PAY003',
        ]);

        // Create RH user
        User::create([
            'name' => 'Marie RH',
            'email' => 'rh@clocation.com',
            'password' => Hash::make('rh123456'),
            'firstName' => 'Marie',
            'lastName' => 'Ressources',
            'role' => 'rh',
            'status' => 'approved',
            'department' => 'Ressources Humaines',
            'position' => 'Responsable RH',
            'phone' => '+1234567893',
            'address' => '321 RH Boulevard',
            'hireDate' => now()->subMonths(6),
            'salary' => 55000.00,
            'contractStart' => now()->subMonths(6),
            'contractEnd' => now()->addYears(2),
            'medicalVisitStart' => now()->subMonths(6),
            'medicalVisitEnd' => now()->addMonths(6),
            'derogationStart' => null,
            'derogationEnd' => null,
            'inductionStart' => now()->subMonths(6),
            'inductionEnd' => now()->subMonths(6)->addDays(14),
            'cnssNumber' => 'CNSS004',
            'payrollNumber' => 'PAY004',
        ]);

        // Create Logisticien user
        User::create([
            'name' => 'Pierre Logistique',
            'email' => 'logisticien@clocation.com',
            'password' => Hash::make('logistique123'),
            'firstName' => 'Pierre',
            'lastName' => 'Transport',
            'role' => 'logisticien',
            'status' => 'approved',
            'department' => 'Logistique',
            'position' => 'Responsable Logistique',
            'phone' => '+1234567894',
            'address' => '654 Logistics Street',
            'hireDate' => now()->subMonths(3),
            'salary' => 50000.00,
            'contractStart' => now()->subMonths(3),
            'contractEnd' => now()->addYears(3),
            'medicalVisitStart' => now()->subMonths(3),
            'medicalVisitEnd' => now()->addMonths(9),
            'derogationStart' => null,
            'derogationEnd' => null,
            'inductionStart' => now()->subMonths(3),
            'inductionEnd' => now()->subMonths(3)->addDays(10),
            'cnssNumber' => 'CNSS005',
            'payrollNumber' => 'PAY005',
        ]);

        // Create Pilote users
        User::create([
            'name' => 'Jean Pilote',
            'email' => 'pilote1@clocation.com',
            'password' => Hash::make('pilote123'),
            'firstName' => 'Jean',
            'lastName' => 'Volant',
            'role' => 'pilote',
            'status' => 'approved',
            'department' => 'Navigation',
            'position' => 'Pilote Principal',
            'phone' => '+1234567895',
            'address' => '123 Marina Boulevard',
            'hireDate' => now()->subMonths(12),
            'salary' => 48000.00,
            'contractStart' => now()->subMonths(12),
            'contractEnd' => now()->addYears(2),
            'medicalVisitStart' => now()->subMonths(6),
            'medicalVisitEnd' => now()->addMonths(6),
            'derogationStart' => null,
            'derogationEnd' => null,
            'inductionStart' => now()->subMonths(12),
            'inductionEnd' => now()->subMonths(12)->addDays(21),
            'cnssNumber' => 'CNSS006',
            'payrollNumber' => 'PAY006',
        ]);

        User::create([
            'name' => 'Marc Navigation',
            'email' => 'pilote2@clocation.com',
            'password' => Hash::make('pilote123'),
            'firstName' => 'Marc',
            'lastName' => 'Navigation',
            'role' => 'pilote',
            'status' => 'approved',
            'department' => 'Navigation',
            'position' => 'Pilote Senior',
            'phone' => '+1234567896',
            'address' => '456 Port Avenue',
            'hireDate' => now()->subMonths(8),
            'salary' => 46000.00,
            'contractStart' => now()->subMonths(8),
            'contractEnd' => now()->addYears(3),
            'medicalVisitStart' => now()->subMonths(2),
            'medicalVisitEnd' => now()->addMonths(10),
            'derogationStart' => null,
            'derogationEnd' => null,
            'inductionStart' => now()->subMonths(8),
            'inductionEnd' => now()->subMonths(8)->addDays(21),
            'cnssNumber' => 'CNSS007',
            'payrollNumber' => 'PAY007',
        ]);

        // Create Mécanicien users
        User::create([
            'name' => 'Paul Mécanicien',
            'email' => 'mecanicien1@clocation.com',
            'password' => Hash::make('mecano123'),
            'firstName' => 'Paul',
            'lastName' => 'Réparation',
            'role' => 'mecanicien',
            'status' => 'approved',
            'department' => 'Maintenance',
            'position' => 'Mécanicien Principal',
            'phone' => '+1234567897',
            'address' => '789 Atelier Street',
            'hireDate' => now()->subMonths(18),
            'salary' => 44000.00,
            'contractStart' => now()->subMonths(18),
            'contractEnd' => now()->addYears(2),
            'medicalVisitStart' => now()->subMonths(6),
            'medicalVisitEnd' => now()->addMonths(6),
            'derogationStart' => null,
            'derogationEnd' => null,
            'inductionStart' => now()->subMonths(18),
            'inductionEnd' => now()->subMonths(18)->addDays(14),
            'cnssNumber' => 'CNSS008',
            'payrollNumber' => 'PAY008',
        ]);

        User::create([
            'name' => 'Luc Technique',
            'email' => 'mecanicien2@clocation.com',
            'password' => Hash::make('mecano123'),
            'firstName' => 'Luc',
            'lastName' => 'Technique',
            'role' => 'mecanicien',
            'status' => 'approved',
            'department' => 'Maintenance',
            'position' => 'Mécanicien Spécialisé',
            'phone' => '+1234567898',
            'address' => '321 Workshop Road',
            'hireDate' => now()->subMonths(6),
            'salary' => 42000.00,
            'contractStart' => now()->subMonths(6),
            'contractEnd' => now()->addYears(3),
            'medicalVisitStart' => now()->subMonths(6),
            'medicalVisitEnd' => now()->addMonths(6),
            'derogationStart' => null,
            'derogationEnd' => null,
            'inductionStart' => now()->subMonths(6),
            'inductionEnd' => now()->subMonths(6)->addDays(14),
            'cnssNumber' => 'CNSS009',
            'payrollNumber' => 'PAY009',
        ]);

        // Create Director user
        User::create([
            'name' => 'Sophie Directrice',
            'email' => 'director@clocation.com',
            'password' => Hash::make('director123'),
            'firstName' => 'Sophie',
            'lastName' => 'Direction',
            'role' => 'director',
            'status' => 'approved',
            'department' => 'Direction',
            'position' => 'Directrice Générale',
            'phone' => '+1234567899',
            'address' => '100 Executive Plaza',
            'hireDate' => now()->subYears(2),
            'salary' => 85000.00,
            'contractStart' => now()->subYears(2),
            'contractEnd' => now()->addYears(3),
            'medicalVisitStart' => now()->subMonths(12),
            'medicalVisitEnd' => now(),
            'derogationStart' => null,
            'derogationEnd' => null,
            'inductionStart' => now()->subYears(2),
            'inductionEnd' => now()->subYears(2)->addDays(7),
            'cnssNumber' => 'CNSS010',
            'payrollNumber' => 'PAY010',
        ]);
    }
}
